# Lab 4

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/giswqs/geog-510/blob/main/book/labs/lab_04.ipynb)

## Exercise 1: Variable Assignment and Basic Operations

Create variables to store the following geospatial data:

- The latitude and longitude of New York City: 40.7128, -74.0060.
- The population of New York City: 8,336,817.
- The area of New York City in square kilometers: 783.8.

Perform the following tasks:

1. Calculate and print the population density of New York City (population per square kilometer).
2. Print the coordinates in the format "Latitude: [latitude], Longitude: [longitude]".

In [ ]:
latitude, longitude = 40.7128, -74.0060
population = 8336817
area = 783.8
population_density = population / area
print(f"Population Density: {population_density:.2f} per km²")
print(f"Latitude: {latitude:.4f}, Longitude: {longitude:.4f}")

Population Density: 10636.41 per km²
Latitude: 40.7128, Longitude: -74.0060


## Exercise 2: Working with Strings

Create a string variable to store the name of a city, such as "San Francisco". Perform the following operations:

1. Convert the string to lowercase and print the result.
2. Convert the string to uppercase and print the result.
3. Replace "San" with "Los" in the city name and print the new string.

In [ ]:
city_name = "San Francisco"
print(city_name.lower())
print(city_name.upper())
print(city_name.replace("San", "Los"))

san francisco
SAN FRANCISCO
Los Francisco


## Exercise 3: Using Lists

Create a list of tuples, where each tuple contains the name of a city and its corresponding latitude and longitude:

- New York City: (40.7128, -74.0060)
- Los Angeles: (34.0522, -118.2437)
- Chicago: (41.8781, -87.6298)

Perform the following tasks:

1. Add a new city (e.g., Miami: (25.7617, -80.1918)) to the list.
2. Print the entire list of cities.
3. Slice the list to print only the first two cities.

In [ ]:
cities = [("New York City", (40.7128, -74.0060)),
          ("Los Angeles", (34.0522, -118.2437)),
          ("Chicago", (41.8781, -87.6298))]
cities.append(("Miami", (25.7617, -80.1918)))
print(cities)
print(cities[:2])

[('New York City', (40.7128, -74.006)), ('Los Angeles', (34.0522, -118.2437)), ('Chicago', (41.8781, -87.6298)), ('Miami', (25.7617, -80.1918))]
[('New York City', (40.7128, -74.006)), ('Los Angeles', (34.0522, -118.2437))]


## Exercise 4: Using Tuples

Create a tuple to store the coordinates (latitude, longitude) of the Eiffel Tower: (48.8584, 2.2945). Perform the following tasks:

1. Access and print the latitude and longitude values from the tuple.
2. Try to change the latitude value to 48.8585. What happens? Explain why.

In [ ]:
eiffel_tower = (48.8584, 2.2945)
print(f"Las coordenadas de la Torre Eiffel son: Latitud: {eiffel_tower[0]}, Longitud: {eiffel_tower[1]}")
#Tuples ares inmutable in python, you can´t change it beacuase it raise an error.

Las coordenadas de la Torre Eiffel son: Latitud: 48.8584, Longitud: 2.2945


## Exercise 5: Working with Sets

Create a set of countries you have visited, such as {"USA", "France", "Germany"}. Perform the following tasks:

1. Add a new country to the set.
2. Try to add the same country again. What happens?
3. Print the updated set.

In [ ]:
visited_countries = {"USA", "France", "Germany","Poland","Portugal","UK","Belgium","The Netherlands"}
visited_countries.add("Italy")
visited_countries.add("Italy")  #  sets in Python do not allow duplicate values, in fact it is a way structure to prevent it.
print(visited_countries)

{'Portugal', 'USA', 'France', 'Belgium', 'UK', 'The Netherlands', 'Poland', 'Germany', 'Italy'}


## Exercise 6: Working with Dictionaries

Create a dictionary to store information about a specific geospatial feature, such as a river:

- Name: "Amazon River"
- Length: 6400 km
- Countries: ["Brazil", "Peru", "Colombia"]

Perform the following tasks:

1. Add a new key-value pair to the dictionary to store the river's average discharge (e.g., 209,000 m³/s).
2. Update the length of the river to 6992 km.
3. Print the dictionary.

In [ ]:
river = {"Name": "Amazon River", "Length": 6400, "Countries": ["Brazil", "Peru", "Colombia"]}
river["Discharge"] = 209000
river["Length"] = 6992
print(river)

{'Name': 'Amazon River', 'Length': 6992, 'Countries': ['Brazil', 'Peru', 'Colombia'], 'Discharge': 209000}


## Exercise 7: Nested Data Structures

Create a dictionary to represent a city that contains the city's name, population, and coordinates (latitude, longitude):

- Name: "Tokyo"
- Population: 13,515,271
- Coordinates: (35.6895, 139.6917)

Perform the following tasks:

1. Access and print the population of the city.
2. Access and print the city's latitude.
3. Update the population to 14,000,000 and print the updated dictionary.

In [ ]:
tokyo = {"Name": "Tokyo", "Population": 13515271, "Coordinates": (35.6895, 139.6917)}
print(tokyo["Population"])
print(tokyo["Coordinates"][0])
tokyo["Population"] = 14000000
print(tokyo)

13515271
35.6895
{'Name': 'Tokyo', 'Population': 14000000, 'Coordinates': (35.6895, 139.6917)}


## Exercise 8: List Operations

Given the list of cities from Exercise 3, perform the following operations:

1. Sort the list of cities alphabetically by name.
2. Create a new list that contains only the city names.
3. Remove the last city from the original list and print the updated list.

In [ ]:
cities = [("New York City", (40.7128, -74.0060)),
          ("Los Angeles", (34.0522, -118.2437)),
          ("Chicago", (41.8781, -87.6298))]
cities.sort()  # Sort alphabetically
print(cities)
city_names = [city[0] for city in cities]
print(city_names)
cities.pop()
print(cities)

[('Chicago', (41.8781, -87.6298)), ('Los Angeles', (34.0522, -118.2437)), ('New York City', (40.7128, -74.006))]
['Chicago', 'Los Angeles', 'New York City']
[('Chicago', (41.8781, -87.6298)), ('Los Angeles', (34.0522, -118.2437))]


## Exercise 9: Dictionary Operations

Using the dictionary from Exercise 6, perform the following tasks:

1. Check if the key "Length" exists in the dictionary.
2. Print all the keys in the dictionary.
3. Print all the values in the dictionary.

In [ ]:
river = {"Name": "Amazon River", "Length": 6400, "Countries": ["Brazil", "Peru", "Colombia"]}
print("Length" in river)
print(river.keys())
print(river.values())

True
dict_keys(['Name', 'Length', 'Countries'])
dict_values(['Amazon River', 6400, ['Brazil', 'Peru', 'Colombia']])


## Exercise 10: Practical Application

Imagine you have a list of tuples, each representing a location with its name, latitude, and longitude:

In [2]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]



Perform the following tasks:

1. Create a new list that contains only the names of the locations.
2. Create a dictionary where the keys are location names and the values are tuples of their coordinates.
3. Print the latitude of "K2" using the dictionary.

In [ ]:
location_names = [name for name,_,_ in locations]
location_dict = {name:(lat,lon) for name,lat,lon in locations}
k2_lat = location_dict ["K2"][0]

print("Nombres:", location_names)
print("Diccionario:", location_dict)
print("Latitud de K2:", k2_lat)



Nombres: ['Mount Everest', 'K2', 'Kangchenjunga']
Diccionario: {'Mount Everest': (27.9881, 86.925), 'K2': (35.8808, 76.5155), 'Kangchenjunga': (27.7025, 88.1475)}
Latitud de K2: 35.8808


## Exercise 11: Manipulating Geographic Location Strings

- Create a string that represents the name of a geographic feature (e.g., `"Amazon River"`).
- Convert the string to lowercase and then to uppercase.
- Concatenate the string with the name of the country (e.g., `"Brazil"`) to create a full location name.
- Repeat the string three times, separating each repetition with a dash (`-`).

In [ ]:
geo_feature = "Amazon River"
print(geo_feature.lower())
print(geo_feature.upper())
print(geo_feature + " - Brazil")
print((geo_feature + " - ") * 2 + geo_feature)

amazon river
AMAZON RIVER
Amazon River - Brazil
Amazon River - Amazon River - Amazon River


## Exercise 12: Extracting and Formatting Coordinates

- Given a string with the format `"latitude, longitude"` (e.g., `"40.7128N, 74.0060W"`), extract the numeric values of latitude and longitude.
- Convert these values to floats and remove the directional indicators (`N`, `S`, `E`, `W`).
- Format the coordinates into a `POINT` WKT string (e.g., `"POINT(-74.0060 40.7128)"`).

In [ ]:
coord_str = "40.7128N, 74.0060W"
lat, lon = coord_str[:-1].split(', ')
lat, lon = float(lat[:-1]), -float(lon[:-1])
print(f"POINT({lon} {lat})")

POINT(-74.006 40.7128)


## Exercise 13: Building Dynamic SQL Queries

- Given a table name and a condition, dynamically build an SQL query string.
- Example: If `table_name = "cities"` and `condition = "population > 1000000"`, the query should be `"SELECT * FROM cities WHERE population > 1000000;"`.
- Add additional conditions dynamically, like `AND` clauses.

In [ ]:
def build_query(table_name, condition, additional_conditions=None):
    if additional_conditions is None:
        additional_conditions = []
    query = f"SELECT * FROM {table_name} WHERE {condition}"
    for cond in additional_conditions:
        query += f" AND {cond}"
    return query

print(build_query("cities", "population > 1000000", ["area < 5000", "density > 1000"]))

SELECT * FROM cities WHERE population > 1000000 AND area < 5000 AND density > 1000


## Exercise 14: String Normalization and Cleaning

- Given a list of city names with inconsistent formatting (e.g., `[" new york ", "Los ANGELES", "   CHICAGO"]`), normalize the names by:
  - Stripping any leading or trailing whitespace.
  - Converting them to title case (e.g., `"New York"`, `"Los Angeles"`, `"Chicago"`).
- Ensure that the output is a clean list of city names.

In [ ]:
city_list = [" new york ", "Los ANGELES", "   CHICAGO"]
cleaned_cities = [city.strip().title() for city in city_list]
print(cleaned_cities)

['New York', 'Los Angeles', 'Chicago']


## Exercise 15: Parsing and Extracting Address Information

- Given a string in the format `"Street, City, Country"` (e.g., `"123 Main St, Springfield, USA"`), write a function that parses the string into a dictionary with keys `street`, `city`, and `country`.
- The function should return a dictionary like `{"street": "123 Main St", "city": "Springfield", "country": "USA"}`.

In [ ]:
def parse_address(address):
    street, city, country = [part.strip() for part in address.split(",")]
    return {"street": street, "city": city, "country": country}
#example
address = "170 Horreo, Santiago de Compostela, España"
print(parse_address(address))


{'street': '170 Horreo', 'city': 'Santiago de Compostela', 'country': 'España'}


## Exercise 16: Using For Loops to Process Coordinate Lists

- Create a list of tuples representing coordinates (latitude, longitude).
- Write a `for` loop that prints each coordinate and indicates whether it is in the Northern or Southern Hemisphere based on the latitude.

In [ ]:


coordinates = [
    (34.0522, -118.2437),  # Los Angeles
    (-33.8688, 151.2093),  # Sydney
    (48.8566, 2.3522),    # Paris
    (-22.9068, -43.1729)   # Rio de Janeiro
]

for lat, lon in coordinates:
    hemisphere = "Northern" if lat >= 0 else "Southern"
    print(f"Latitude: {lat}, Longitude: {lon} ({hemisphere} Hemisphere)")


Latitude: 34.0522, Longitude: -118.2437 (Northern Hemisphere)
Latitude: -33.8688, Longitude: 151.2093 (Southern Hemisphere)
Latitude: 48.8566, Longitude: 2.3522 (Northern Hemisphere)
Latitude: -22.9068, Longitude: -43.1729 (Southern Hemisphere)


## Exercise 17: While Loops for Iterative Processing

- Create a list of coordinates (latitude, longitude).
- Write a `while` loop that continues to print each coordinate until it encounters a coordinate with a negative latitude.
- Stop the loop once this condition is met.

In [3]:
coordinates = [
    (34.0522, -118.2437),  # Los Angeles
    (-33.8688, 151.2093),  # Sydney
    (48.8566, 2.3522),    # Paris
    (-22.9068, -43.1729)   # Rio de Janeiro
]

i = 0
while i < len(coordinates) and coordinates[i][0] >= 0:
    lat, lon = coordinates[i]
    print(f"Latitude: {lat}, Longitude: {lon}")
    i += 1


Latitude: 34.0522, Longitude: -118.2437


## Exercise 18: Conditional Logic in Loops

- Create a list of coordinates and use a `for` loop to iterate over them.
- Use an `if-elif-else` statement inside the loop to classify each coordinate based on its longitude:
  - Print `"Eastern Hemisphere"` if the longitude is greater than 0.
  - Print `"Western Hemisphere"` if the longitude is less than 0.

In [4]:
coordinates = [
    (34.0522, -118.2437),  # Los Angeles
    (-33.8688, 151.2093),  # Sydney
    (48.8566, 2.3522),    # Paris
    (-22.9068, -43.1729)   # Rio de Janeiro
]


for lat, lon in coordinates:
    if lon > 0:
        print("Eastern Hemisphere")
    elif lon < 0:
        print("Western Hemisphere")
    else:
        print("Prime Meridian")

Western Hemisphere
Eastern Hemisphere
Eastern Hemisphere
Western Hemisphere


## Exercise 19: Filtering Data with Combined Loops and Conditionals

- Given a list of coordinates, filter out and store only those located in the Southern Hemisphere (latitude < 0).
- Count the number of coordinates that meet this condition and print the result.

In [5]:
coordinates = [
    (34.0522, -118.2437),  # Los Angeles
    (-33.8688, 151.2093),  # Sydney
    (48.8566, 2.3522),    # Paris
    (-22.9068, -43.1729)   # Rio de Janeiro
]


southern_coords = [coord for coord in coordinates if coord[0] < 0]
print(f"Southern Hemisphere coordinates count: {len(southern_coords)}")

Southern Hemisphere coordinates count: 2


## Exercise 20: Generating and Analyzing Random Coordinates

- Write a program that generates random coordinates (latitude between [-90, 90] degrees and longitude between [-180, 180] degrees).
- Use a `while` loop to keep generating coordinates until a pair with both latitude and longitude greater than 50 is generated.
- Print each generated coordinate and the final coordinate that meets the condition.

In [6]:
import random
while True:
    lat, lon = random.uniform(-90, 90), random.uniform(-180, 180)
    print(f"Generated Coordinate: ({lat:.4f}, {lon:.4f})")
    if lat > 50 and lon > 50:
        print(f"Final Coordinate: ({lat:.4f}, {lon:.4f}) meets the condition.")
        break

Generated Coordinate: (86.9067, -125.8066)
Generated Coordinate: (47.9185, 131.2252)
Generated Coordinate: (20.6700, 155.8012)
Generated Coordinate: (-12.6240, -104.7981)
Generated Coordinate: (40.2889, -121.4084)
Generated Coordinate: (-63.5105, 60.2349)
Generated Coordinate: (12.0655, -79.4121)
Generated Coordinate: (-3.7317, -49.7273)
Generated Coordinate: (74.4113, 106.1122)
Final Coordinate: (74.4113, 106.1122) meets the condition.


## Submission Requirements

Complete the exercises above and and upload the notebook to your GitHub repository. Make sure the notebook has a Colab badge at the top so that it can be easily opened in Google Colab. Submit the URL of the notebook to Canvas.